---
# tasks file for kube
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: repositories
    dest:  /etc/apk/
    owner: root
    group: root
    mode: '0644'


- name: install packages
  community.general.apk:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker

# - name: Copy file with owner and permissions
#   ansible.builtin.copy:
#     src: k8s.conf
#     dest:  /etc/modules-load.d/
#     owner: root
#     group: root
#     mode: '0644'


# - name: config br_netfilter
#   ansible.posix.sysctl:
#     name: "{{ item }}"
#     value: '1'
#     sysctl_set: yes
#     reload: yes
#   loop:
#     - net.bridge.bridge-nf-call-iptables
#     - net.bridge.bridge-nf-call-ip6tables
#     - net.ipv4.ip_forward
  

# - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
#   replace:
#     path: /etc/fstab
#     regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
#     replace: '# \1'
#   # when: kubernetes_installed is changed

