---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/asg1612/docker-systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
