---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: alpine-3.12
    image: docker.io/mesaguy/ansible-molecule-alpine:alpine-3.12
    #override_command: false
    privileged: true
    #pre_build_image: true
    #pull: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
verifier:
  name: ansible
